[package]
name = "some-game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
ash = "0.38.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
winit = "0.30.5"
rpgs = { path = "../rpgs" }
