[package]
name = "some-game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
ash = "0.38.0"
winit = "0.30.5"
rpgs = { path = "../rpgs" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
